### ISSUE TITLE
for python2 key0.encrypt(input_data, iv, padding=True)

### ISSUE THREAD

**Issue by wzsx150** [0x10001/sm4#1]
bugs?
python2.7:   key0.encrypt(input_data, iv, padding=True)

  File "D:\Python27\lib\site-packages\sm4\base.py", line 63, in guard_message
    return message.ljust(length + 16 >> 4 << 4, bytes((16 - (length & 15), )))
TypeError: ljust() argument 2 must be char, not str

----------------
maybe code for python2 should be:
return message.ljust(length + 16 >> 4 << 4, chr((16 - (length & 15))))

or better  for python2 and python3

**Comment by 0x10001** [comment]
Thank you!

It is a compatibility problem between Python 2 and 3, and I wrote it in Python 3. This issue exists in another encryption package called `des`. It seems that most users prefer Python 3, so this issue didn't get revealed.

The solution you have suggested works fine with Python 2, but that's not the case for Python 3. Anyway, this will get fixed in some days.

**Comment by 0x10001** [comment]
Thank you!

It is a compatibility problem between Python 2 and 3, and I wrote it in Python 3. This issue exists in another encryption package called `des`. It seems that most users prefer Python 3, so this issue didn't get revealed.

The solution you have suggested works fine with Python 2, but that's not the case for Python 3. Anyway, this will get fixed in some days.
